### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by trbjo** [XanClic/krunner-mpd#9]
Hi

I use:

* mpd and Cantata
* Arch Linux
* KDE Plasma 5.13

I installed the package from AUR and configured the file in ~/.config/krunner-mpd/config.yaml with the following info:

`mpd`
`    port: 65511`

But none of the keywords (play/pause/next/previous) seem to trigger anything in krunner. How do I activate it?

**Comment by XanClic** [comment]
Hi,

Did you restart krunner after the installation, and is the plugin enabled in the krunner settings?

**Comment by VirgiliusHaufniensis** [comment]
Hi, 

Yes and yes. 

The problem seems to be mpd related:

/usr/lib/ruby/gems/2.5.0/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:273:in `initialize': Connection refused - connect(2) for "localhost" port 65511 (Errno::ECONNREFUSED)
	from /usr/lib/ruby/gems/2.5.0/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:273:in `new'
	from /usr/lib/ruby/gems/2.5.0/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:273:in `socket'
	from /usr/lib/ruby/gems/2.5.0/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:104:in `connect'
	from /usr/bin/krunner-mpd:183:in `<main>'

**Comment by XanClic** [comment]
OK, thank you. Unfortunately I don’t have any further insight into how ruby-mpd works, so I get as much information from that backtrace as you probably do; which is “It looks like there is no mpd instance running on thart port on your local machine”.
So I’m afraid I can’t help you much with debugging that specific issue, I can only come up with standard ideas. :-/
I mean, if cantata works, I suppose that proves the MPD instance is working. Can you connect to it with mpc -h localhost -p 6600? Maybe MPD is listening on a specific IP address that “localhost” for some reason does not resolve to…?

(Maybe your intention is to start MPD independently of this krunner script? That would be a feature that’s currently missing, as MPD needs to be started before krunner-mpd or at the latest ten seconds later. I suppose it should be easily possible to implement looking for mpd on-demand and not requiring it at startup.)
